CREATE TABLE STUD
(
SID INT,
SNAME VARCHAR(25),
DOB VARCHAR(12),
PHY INT,
CHEM INT,
MATHS INT
);

INSERT INTO STUD VALUES(1071,'KIRAN','1997-06-15',65,71,70),
(1056,'ABHIJITH','1998-07-12',85,92,68),(1098,'DEVJI','1998-11-12',73,77,68),
(1154,'TUTTU','1998-09-04',75,70,64);
SELECT * FROM STUD;
SELECT SID,SNAME FROM STUD  WHERE DOB=(SELECT MAX(DOB) FROM STUD);

SELECT * FROM STUD WHERE MATHS >=40 AND (PHY >=40 OR CHEM >=40);
ALTER TABLE STUD ADD TOTAL int;
ALTER TABLE STUD ADD AVERAGE float(10,3);
DESCRIBE STUD;

SELECT SNAME FROM STUD WHERE MATHS=(SELECT max(MATHS) FROM STUD);
SELECT SNAME FROM STUD WHERE CHEM=(SELECT min(CHEM) FROM STUD);
UPDATE STUD SET TOTAL=PHY+CHEM+MATHS;
SELECT * FROM STUD;
UPDATE STUD SET AVERAGE=TOTAL/3;
SELECT * FROM STUD;
SELECT * FROM STUD ORDER BY TOTAL DESC;

ALTER TABLE STUD RENAME COLUMN AVERAGE TO Avg_Mark;
SELECT * FROM STUD;
SELECT *FROM STUD WHERE Avg_Mark > (SELECT AVG(Avg_Mark) FROM STUD);
DROP TABLE STUD;

